//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Portal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Portal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Portal", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actions.
        /// </summary>
        internal static string DashboardActionsBtnText {
            get {
                return ResourceManager.GetString("DashboardActionsBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clone.
        /// </summary>
        internal static string DashboardCloneBtnText {
            get {
                return ResourceManager.GetString("DashboardCloneBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preview in gallery.
        /// </summary>
        internal static string DashboardGalleryPreviewBtnText {
            get {
                return ResourceManager.GetString("DashboardGalleryPreviewBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to owners.
        /// </summary>
        internal static string DashboardOwnersBtnText {
            get {
                return ResourceManager.GetString("DashboardOwnersBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verify.
        /// </summary>
        internal static string DashboardStatusCheckerBtnText {
            get {
                return ResourceManager.GetString("DashboardStatusCheckerBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        internal static string DashboardSubmissionFormBtnText {
            get {
                return ResourceManager.GetString("DashboardSubmissionFormBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string DashboardSubmissionIDHeader {
            get {
                return ResourceManager.GetString("DashboardSubmissionIDHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App ID.
        /// </summary>
        internal static string DashboardSubmissionNicknameHeader {
            get {
                return ResourceManager.GetString("DashboardSubmissionNicknameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string DashboardSubmissionStatusHeader {
            get {
                return ResourceManager.GetString("DashboardSubmissionStatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        internal static string DashboardSubmissionVersionHeader {
            get {
                return ResourceManager.GetString("DashboardSubmissionVersionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Welcome! From this page you can:&lt;p&gt;&lt;ul&gt;&lt;li&gt;Edit your previous submissions.&lt;/li&gt;&lt;li&gt;Test the validity of your application data.&lt;/li&gt;&lt;li&gt;Designate co-owners for your submissions.&lt;/li&gt;&lt;li&gt;Edit your &lt;a href=&quot;/profile&quot; title=&quot;edit your contact information&quot;&gt;contact information&lt;/a&gt;.&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        internal static string MyAppsIntroMsg {
            get {
                return ResourceManager.GetString("MyAppsIntroMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web App Gallery Submission Portal.
        /// </summary>
        internal static string MyAppsTitle {
            get {
                return ResourceManager.GetString("MyAppsTitle", resourceCulture);
            }
        }
    }
}
