//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionTransaction
    {
        public int SubmissionTransactionID { get; set; }
        public int SubmissionID { get; set; }
        public int SubmissionTaskID { get; set; }
        public string Description { get; set; }
        public System.DateTime RecordedAt { get; set; }
    }
}
