//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmittersContactDetail
    {
        public int SubmitterID { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string Title { get; set; }
        public string EMail { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string StateOrProvince { get; set; }
        public string ZipOrRegionCode { get; set; }
        public string Country { get; set; }
        public Nullable<int> DirectContactMethodID1 { get; set; }
        public string DirectData1 { get; set; }
        public Nullable<int> DirectContactMethodID2 { get; set; }
        public string DirectData2 { get; set; }
    }
}
