//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webgallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChapterLog
    {
        public int ChapterLogId { get; set; }
        public int TrainingLogId { get; set; }
        public int Chapter { get; set; }
        public bool Click { get; set; }
    
        public virtual TrainingLog TrainingLog { get; set; }
    }
}
