//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentIndex
    {
        public string ContentId { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Channel { get; set; }
    }
}
