//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hosters_HostingProviderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hosters_HostingProviderDetail()
        {
            this.Hosters_HostingProviderOwner = new HashSet<Hosters_HostingProviderOwner>();
            this.Hosters_HostingProviderLogo = new HashSet<Hosters_HostingProviderLogo>();
            this.Hosters_TargetedCountry = new HashSet<Hosters_TargetedCountry>();
            this.Hosters_Offers = new HashSet<Hosters_Offers>();
        }
    
        public int HosterId { get; set; }
        public string HostingProviderName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public int CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public int CityId { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string WebsiteURL { get; set; }
        public Nullable<int> SPLAID { get; set; }
        public Nullable<bool> IsPartner { get; set; }
        public Nullable<int> PartnerTypeId { get; set; }
        public int ActiveStatusId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string HosterProviderDescription { get; set; }
        public Nullable<bool> IsSellingToReseller { get; set; }
        public string WebsiteSparkID { get; set; }
        public string TechnicalContactName { get; set; }
        public string TechnicalContactEmail { get; set; }
        public string TechnicalContactPhone { get; set; }
    
        public virtual Hosters_ActiveStatus Hosters_ActiveStatus { get; set; }
        public virtual Hosters_City Hosters_City { get; set; }
        public virtual Hosters_Country Hosters_Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosters_HostingProviderOwner> Hosters_HostingProviderOwner { get; set; }
        public virtual Hosters_PartnerTypes Hosters_PartnerTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosters_HostingProviderLogo> Hosters_HostingProviderLogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosters_TargetedCountry> Hosters_TargetedCountry { get; set; }
        public virtual Hosters_State Hosters_State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosters_Offers> Hosters_Offers { get; set; }
    }
}
