//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hosters_CustomField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hosters_CustomField()
        {
            this.Hosters_CustomFieldDomainValue = new HashSet<Hosters_CustomFieldDomainValue>();
            this.Hosters_OfferCustomFieldValue = new HashSet<Hosters_OfferCustomFieldValue>();
            this.Hosters_LocalisedCustomFields = new HashSet<Hosters_LocalisedCustomFields>();
        }
    
        public int CustomFieldId { get; set; }
        public string CustomFieldName { get; set; }
        public int CustomFieldTypeId { get; set; }
        public int ValidationId { get; set; }
        public int CustomFieldOrder { get; set; }
        public bool IsRecommended { get; set; }
        public bool IsActive { get; set; }
        public bool IsMandatory { get; set; }
        public bool IsSearchable { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual Hosters_CustomFieldType Hosters_CustomFieldType { get; set; }
        public virtual Hosters_Validation Hosters_Validation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosters_CustomFieldDomainValue> Hosters_CustomFieldDomainValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosters_OfferCustomFieldValue> Hosters_OfferCustomFieldValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosters_LocalisedCustomFields> Hosters_LocalisedCustomFields { get; set; }
    }
}
