//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hosters_Offers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hosters_Offers()
        {
            this.Hosters_CloudOfferCategoryDetail = new HashSet<Hosters_CloudOfferCategoryDetail>();
            this.Hosters_CloudOfferXmlPrice = new HashSet<Hosters_CloudOfferXmlPrice>();
            this.Hosters_CustomFeature = new HashSet<Hosters_CustomFeature>();
            this.Hosters_FeaturedOffer = new HashSet<Hosters_FeaturedOffer>();
            this.Hosters_OfferCountry = new HashSet<Hosters_OfferCountry>();
            this.Hosters_OfferCountryAdminExclude = new HashSet<Hosters_OfferCountryAdminExclude>();
            this.Hosters_OfferCustomFieldValue = new HashSet<Hosters_OfferCustomFieldValue>();
            this.Hosters_OfferProfile = new HashSet<Hosters_OfferProfile>();
            this.Hosters_Review = new HashSet<Hosters_Review>();
        }
    
        public int OfferId { get; set; }
        public int HosterId { get; set; }
        public string OfferName { get; set; }
        public string Description { get; set; }
        public int HostingTypeId { get; set; }
        public string RestrictionDetails { get; set; }
        public bool IsRecommended { get; set; }
        public double Price { get; set; }
        public Nullable<int> SqlDbCount { get; set; }
        public int HardDiskSpace { get; set; }
        public Nullable<int> EmailIdCount { get; set; }
        public bool IsFullTimeSupport { get; set; }
        public bool Uptime { get; set; }
        public Nullable<int> Bandwidth { get; set; }
        public int StatusId { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string SignUpURL { get; set; }
        public Nullable<System.DateTime> OfferExpiryDate { get; set; }
        public int OfferPriceFrequencyId { get; set; }
        public Nullable<int> RAM { get; set; }
        public string Processor { get; set; }
        public Nullable<int> ExternalIPCount { get; set; }
        public Nullable<bool> HasRestrictions { get; set; }
        public Nullable<bool> Promotional { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public string RejectedReason { get; set; }
        public Nullable<double> SetupFee { get; set; }
        public Nullable<bool> IsWebsiteSpark { get; set; }
        public string PromoText1 { get; set; }
        public string PromoText2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosters_CloudOfferCategoryDetail> Hosters_CloudOfferCategoryDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosters_CloudOfferXmlPrice> Hosters_CloudOfferXmlPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosters_CustomFeature> Hosters_CustomFeature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosters_FeaturedOffer> Hosters_FeaturedOffer { get; set; }
        public virtual Hosters_HostingProviderDetail Hosters_HostingProviderDetail { get; set; }
        public virtual Hosters_HostingType Hosters_HostingType { get; set; }
        public virtual Hosters_OfferActiveStatus Hosters_OfferActiveStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosters_OfferCountry> Hosters_OfferCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosters_OfferCountryAdminExclude> Hosters_OfferCountryAdminExclude { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosters_OfferCustomFieldValue> Hosters_OfferCustomFieldValue { get; set; }
        public virtual Hosters_OfferPriceFrequency Hosters_OfferPriceFrequency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosters_OfferProfile> Hosters_OfferProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosters_Review> Hosters_Review { get; set; }
    }
}
