//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hosters_CloudOfferCategoryDetail
    {
        public int CategoryDetailId { get; set; }
        public int CategoryId { get; set; }
        public int OfferId { get; set; }
        public string CategoryDetailValue { get; set; }
    
        public virtual Hosters_CloudOfferCategory Hosters_CloudOfferCategory { get; set; }
        public virtual Hosters_Offers Hosters_Offers { get; set; }
    }
}
