//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webgallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hosters_OfferProfile
    {
        public int SerialId { get; set; }
        public Nullable<int> OfferId { get; set; }
        public byte[] profileXML { get; set; }
        public string fileName { get; set; }
    
        public virtual Hosters_Offers Hosters_Offers { get; set; }
    }
}
