//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hosters_TargetedCountry
    {
        public int SerialId { get; set; }
        public Nullable<int> HosterId { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual Hosters_Country Hosters_Country { get; set; }
        public virtual Hosters_HostingProviderDetail Hosters_HostingProviderDetail { get; set; }
    }
}
