//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webgallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hosters_HostingTypeTileField
    {
        public int HostingTypeTileFieldId { get; set; }
        public int TileFieldId { get; set; }
        public int HostingTypeId { get; set; }
        public int TileOrder { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual Hosters_HostingType Hosters_HostingType { get; set; }
        public virtual Hosters_TileFields Hosters_TileFields { get; set; }
    }
}
