//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webgallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hosters_HostingProviderOwner
    {
        public int HostingProviderOwnerId { get; set; }
        public int HosterId { get; set; }
        public string Puid { get; set; }
        public bool IsAdmin { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string ASPNETuser { get; set; }
    
        public virtual Hosters_HostingProviderDetail Hosters_HostingProviderDetail { get; set; }
    }
}
