//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webgallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int PackageID { get; set; }
        public int ArchitectureTypeID { get; set; }
        public string PackageURL { get; set; }
        public string StartPage { get; set; }
        public string MD5Hash { get; set; }
        public string SHA1Hash { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string Language { get; set; }
        public Nullable<int> SubmissionID { get; set; }
    }
}
