//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webgallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdDownloadStatsINVALID
    {
        public System.DateTime When { get; set; }
        public string ProdID { get; set; }
        public string Version { get; set; }
        public Nullable<int> ArchitectureTypeID { get; set; }
        public string Language { get; set; }
        public string Country { get; set; }
        public string Referrer { get; set; }
        public int Count { get; set; }
    }
}
