//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        public int SubmissionID { get; set; }
        public string Nickname { get; set; }
        public string Version { get; set; }
        public string SubmittingEntity { get; set; }
        public string SubmittingEntityURL { get; set; }
        public string AppURL { get; set; }
        public string SupportURL { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public Nullable<int> FrameworkOrRuntimeID { get; set; }
        public string DatabaseServerIDs { get; set; }
        public string WebServerExtensionIDs { get; set; }
        public string CategoryID1 { get; set; }
        public string CategoryID2 { get; set; }
        public int LogoID { get; set; }
        public Nullable<int> ScreenshotID1 { get; set; }
        public Nullable<int> ScreenshotID2 { get; set; }
        public Nullable<int> ScreenshotID3 { get; set; }
        public Nullable<int> ScreenshotID4 { get; set; }
        public Nullable<int> ScreenshotID5 { get; set; }
        public Nullable<int> ScreenshotID6 { get; set; }
        public string ProfessionalServicesURL { get; set; }
        public string CommercialProductURL { get; set; }
        public bool AgreedToTerms { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    
        public virtual ApplicationInGallery ApplicationInGallery { get; set; }
        public virtual ApplicationInGallery ApplicationInGallery1 { get; set; }
    }
}
