//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webgallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnconfirmedSubmissionOwner
    {
        public int UnconfirmedSubmissionOwnerID { get; set; }
        public int SubmissionID { get; set; }
        public System.Guid RequestID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> IsSuperSubmitterRequest { get; set; }
    }
}
