//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGallery.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebGalleryDbContext : DbContext
    {
        public WebGalleryDbContext()
            : base("name=WebGalleryDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationInGallery> ApplicationInGalleries { get; set; }
        public virtual DbSet<ArchitectureType> ArchitectureTypes { get; set; }
        public virtual DbSet<BlogPost> BlogPosts { get; set; }
        public virtual DbSet<ChapterLog> ChapterLogs { get; set; }
        public virtual DbSet<CommentModeration> CommentModerations { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<ContentIndex> ContentIndexes { get; set; }
        public virtual DbSet<DatabaseServer> DatabaseServers { get; set; }
        public virtual DbSet<DirectContactMethod> DirectContactMethods { get; set; }
        public virtual DbSet<FrameworksAndRuntime> FrameworksAndRuntimes { get; set; }
        public virtual DbSet<GalleryType> GalleryTypes { get; set; }
        public virtual DbSet<Hosters_Country> Hosters_Country { get; set; }
        public virtual DbSet<Hosters_Region> Hosters_Region { get; set; }
        public virtual DbSet<Hosters_State> Hosters_State { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PageView> PageViews { get; set; }
        public virtual DbSet<ProductOrAppCategory> ProductOrAppCategories { get; set; }
        public virtual DbSet<ProductOrAppImage> ProductOrAppImages { get; set; }
        public virtual DbSet<PullQuote> PullQuotes { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<SubmissionLocalizedMetaData> SubmissionLocalizedMetaDatas { get; set; }
        public virtual DbSet<Submission> Submissions { get; set; }
        public virtual DbSet<SubmissionsStatu> SubmissionsStatus { get; set; }
        public virtual DbSet<SubmissionState> SubmissionStates { get; set; }
        public virtual DbSet<SubmissionTransaction> SubmissionTransactions { get; set; }
        public virtual DbSet<SubmissionTransactionType> SubmissionTransactionTypes { get; set; }
        public virtual DbSet<Submitter> Submitters { get; set; }
        public virtual DbSet<SubmittersContactDetail> SubmittersContactDetails { get; set; }
        public virtual DbSet<TagClick> TagClicks { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TrainingLog> TrainingLogs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WapCommunitySignup> WapCommunitySignups { get; set; }
        public virtual DbSet<WebServerExtension> WebServerExtensions { get; set; }
        public virtual DbSet<AppDownloadStat> AppDownloadStats { get; set; }
        public virtual DbSet<PID> PIDs { get; set; }
        public virtual DbSet<ProdDownloadStat> ProdDownloadStats { get; set; }
        public virtual DbSet<ProdDownloadStatsINVALID> ProdDownloadStatsINVALIDs { get; set; }
        public virtual DbSet<SubmissionOwner> SubmissionOwners { get; set; }
        public virtual DbSet<UnconfirmedSubmissionOwner> UnconfirmedSubmissionOwners { get; set; }
    }
}
